# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_computedracedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedracedata',
            name='average_bike_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computedracedata',
            name='average_finish_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computedracedata',
            name='average_run_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computedracedata',
            name='average_swim_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(choices=[('half-ironman', 'IRONMAN 70.3'), ('full-ironman', 'IRONMAN')], max_length=40),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='bike_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='finish_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='run_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='swim_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
